# All settings related to language and the content of messages will be in this file.
# Currently supported languages:
#  • English (en)
#  • Español (es)
#  • Íslenska (is)
#  • Magyar (hu)
#  • Polskie (pl)
# Note: You MUST type the letters in the parentheses
language: 'en'

# - - - - - - - - - - -
# ~ MESSAGE OVERRIDES ~
# All non-error messages sent by the plugin will appear in the `lang_en` file (and eventually in all other language
#   files as well), and any message that is stored in the language file can be overridden here. To override a message,
#   just add the existing key of the message from the original language file, and set the value to whatever message you
#   would like. A list of all messages can be found here:
#   https://github.com/donvi-bz/JakesRTP/blob/master/Core/src/main/resources/translations/lang_en.yml
# Notes on formatting:
#   To make a line break, type this: \n
#   To use a legacy color code, place an `&` in front of a hex digit (0-9|a-f) like this: &8
#   You can use full hex codes (if you are in the right version of minecraft) like this: {#00FFC8}
# Finally, if you know another language and would like to help translate this plugin, you can copy the `lang_en.yml`
#   file found here https://github.com/donvi-bz/JakesRTP/tree/master/Core/src/main/resources/translations then
#   translate the new language and make a PR. Or you could send me the file another way. Either way, if you do this,
#   thank you so much. ♥

need-to-wait-for-cooldown: 'Whoops! You still have to wait {0}'
